### ISSUE TITLE
Shortcrust / gstreamer

### ISSUE THREAD

**Issue by stuaxo** [gasman/shortcrust#1]
Hi @gasman 

Any idea if I can use shortcrust to create the egl + dispmanx window handle this API expects ?
https://bugzilla.gnome.org/show_bug.cgi?id=772608

I'm pretty new to raspberry pi graphics fundamentals + trying to at least stay in python-land for now.

S

**Comment by gasman** [comment]
Hi @stuaxo - afraid I've not so much as looked at this code in years :-/

I suspect shortcrust doesn't support anything like that as it stands, but hopefully it will be a fairly straightforward addition to https://github.com/gasman/shortcrust/blob/master/shortcrust/raspi/egl.py - the ctypes library ensures that the code in there is a more or less direct translation of the C-level API calls.

**Comment by stuaxo** [comment]
In the end shortcrust, pyopengles and various did help me get some gstreamer stuff working on raspberry pi.

https://gist.github.com/stuaxo/3009b761cba1085ac5730c7485506ee4

Was definitely uphill, having not touched C for a very very long time :)
